apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: crossplane-serviceusage
  namespace: default
spec:
  forProvider:
    project: meshifi-platform
    role: roles/serviceusage.serviceUsageAdmin
    member: serviceAccount:crossplane@meshifi-platform.iam.gserviceaccount.com
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: crossplane-bq
  namespace: default
spec:
  forProvider:
    project: meshifi-platform
    role: roles/bigquery.admin
    member: serviceAccount:crossplane@meshifi-platform.iam.gserviceaccount.com
  providerConfigRef:
    kind: ProviderConfig
    name: default
---