apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: data-product-composition
spec:
  compositeTypeRef:
    apiVersion: meshifi.io/v1alpha1
    kind: DataProduct
  mode: Pipeline
  pipeline:
    - step: pull-extra-resources
      functionRef:
        name: crossplane-contrib-function-extra-resources
      input:
        apiVersion: extra-resources.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          extraResources:
            - kind: DataDomain
              into: DataDomain
              apiVersion: meshifi.io/v1alpha1
              type: Selector
              selector:
                minMatch: 1
                maxMatch: 1
                matchLabels:
                  - key: meshifi.io/data-domain
                    type: FromCompositeFieldPath
                    valueFromFieldPath: spec.dataDomainRef

    - step: validate-data-domain
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |-
            {{- $DataDomain := index (index (index .context "apiextensions.crossplane.io/extra-resources") "DataDomain") 0 }}
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: "{{ .observed.composite.resource.metadata.name }}-validation"
              namespace: "{{ .observed.composite.resource.metadata.namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: validation-check
                gotemplating.fn.crossplane.io/ready: "True"
              labels:
                meshifi.io/data-product: "{{ .observed.composite.resource.metadata.name }}"
            data:
              owner: {{ $DataDomain.spec.owner }}
              status: "validated"
              message: "Data domain reference validation passed"

    - step: create-datasets
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |-
            {{- $datasetTypes := list "raw" "cleaned" "curated" }}
            {{- $first := true }}
            {{- range $datasetType := $datasetTypes }}
            {{- if index $.observed.composite.resource.spec.datasets $datasetType }}
            {{- if not $first }}
            ---
            {{- end }}
            {{- $friendlyName := printf "%s_%s" (replace "-" "_" $.observed.composite.resource.metadata.name) $datasetType }}
            apiVersion: bigquery.gcp.m.upbound.io/v1beta1
            kind: Dataset
            metadata:
              name: "{{ $.observed.composite.resource.metadata.name }}-{{ $datasetType }}"
              namespace: "{{ $.observed.composite.resource.metadata.namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: dataset-{{ $datasetType }}
                crossplane.io/external-name: "{{ $friendlyName }}"
                # gotemplating.fn.crossplane.io/ready: "True"
              labels:
                example.crossplane.io/app: "{{ $.observed.composite.resource.metadata.name }}"
                meshifi.io/data-product: "{{ $.observed.composite.resource.metadata.name }}"
                meshifi.io/data-domain: "{{ $.observed.composite.resource.spec.dataDomainRef }}"
            spec:
              providerConfigRef:
                kind: ProviderConfig
                name: default
              forProvider:
                project: meshifi-platform
                location: australia-southeast1
                friendlyName: {{ $friendlyName }}
            {{- $first = false }}
            {{- end }}
            {{- end }}

    - step: create-sa-and-bindings
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |-
            {{- $serviceAccountName := printf "%s-sa" (replace "_" "-" $.observed.composite.resource.metadata.name) }}
            apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
            kind: ServiceAccount
            metadata:
              name: some-sa
              namespace: "{{ $.observed.composite.resource.metadata.namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: data-product-sa
                gotemplating.fn.crossplane.io/ready: "True"
              labels:
                meshifi.io/data-product: "{{ $.observed.composite.resource.metadata.name }}"
            spec:
              forProvider:
                project: meshifi-platform
                description: "Service account for data product {{ $.observed.composite.resource.metadata.name }}"
              providerConfigRef:
                name: default
                kind: ProviderConfig

            ---
            {{- $datasetTypes := list "raw" "cleaned" "curated" }}
            {{- $first := true }}
            {{- range $datasetType := $datasetTypes }}
            {{- if index $.observed.composite.resource.spec.datasets $datasetType }}
            {{- if not $first }}
            ---
            {{- end }}
            {{- $first = false }}
            apiVersion: bigquery.gcp.m.upbound.io/v1beta1
            kind: DatasetIAMMember
            metadata:
              name: "{{ $.observed.composite.resource.metadata.name }}-{{ $datasetType }}-iam"
              namespace: "{{ $.observed.composite.resource.metadata.namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: dataset-{{ $datasetType }}-iam
              labels:
                example.crossplane.io/app: "{{ $.observed.composite.resource.metadata.name }}"
                meshifi.io/data-product: "{{ $.observed.composite.resource.metadata.name }}"
                meshifi.io/data-domain: "{{ $.observed.composite.resource.spec.dataDomainRef }}"
            spec:
              providerConfigRef:
                kind: ProviderConfig
                name: default
              forProvider:
                project: meshifi-platform
                datasetIdRef:
                  name: "{{ $.observed.composite.resource.metadata.name }}-{{ $datasetType }}"
                role: roles/bigquery.dataEditor
                member: serviceAccount:some-sa@meshifi-platform.iam.gserviceaccount.com
            {{- end }}
            {{- end }}

    - step: automatically-detect-readiness
      functionRef:
        name: crossplane-contrib-function-auto-ready
