apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: data-product-composition
spec:
  compositeTypeRef:
    apiVersion: meshifi.io/v1alpha1
    kind: DataProduct
  mode: Pipeline
  pipeline:
    - step: create-datasets
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |-
            {{- $projectId := .observed.composite.resource.spec.gcp.projectId }}
            {{- $region := .observed.composite.resource.spec.gcp.region | default "us-central1" }}
            {{- $productName := .observed.composite.resource.metadata.name }}
            {{- $namespace := .observed.composite.resource.metadata.namespace }}
            {{- $datasetTypes := list "raw" "cleaned" "curated" }}
            {{- $first := true }}
            {{- range $datasetType := $datasetTypes }}
            {{- if index $.observed.composite.resource.spec.datasets $datasetType }}
            {{- if not $first }}
            ---
            {{- end }}
            {{- $datasetId := printf "%s_%s" (replace "-" "_" $productName) $datasetType }}
            apiVersion: bigquery.gcp.m.upbound.io/v1beta1
            kind: Dataset
            metadata:
              name: "{{ $productName }}-{{ $datasetType }}"
              namespace: "{{ $namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: dataset-{{ $datasetType }}
                crossplane.io/external-name: "{{ $datasetId }}"
              labels:
                meshifi.io/data-product: "{{ $productName }}"
            spec:
              providerConfigRef:
                kind: ProviderConfig
                name: default
              forProvider:
                project: {{ $projectId }}
                location: {{ $region }}
                friendlyName: {{ $datasetId }}
            {{- $first = false }}
            {{- end }}
            {{- end }}

    - step: create-sa-and-bindings
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |-
            {{- $projectId := .observed.composite.resource.spec.gcp.projectId }}
            {{- $productName := .observed.composite.resource.metadata.name }}
            {{- $namespace := .observed.composite.resource.metadata.namespace }}
            {{- $saName := printf "%s-sa" (replace "_" "-" $productName) }}
            {{- $saEmail := printf "%s@%s.iam.gserviceaccount.com" $saName $projectId }}
            apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
            kind: ServiceAccount
            metadata:
              name: {{ $saName }}
              namespace: "{{ $namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: data-product-sa
                crossplane.io/external-name: "{{ $saName }}"
                gotemplating.fn.crossplane.io/ready: "True"
              labels:
                meshifi.io/data-product: "{{ $productName }}"
            spec:
              forProvider:
                project: {{ $projectId }}
                description: "Service account for data product {{ $productName }}"
              providerConfigRef:
                name: default
                kind: ProviderConfig

            ---
            {{- $datasetTypes := list "raw" "cleaned" "curated" }}
            {{- $first := true }}
            {{- range $datasetType := $datasetTypes }}
            {{- if index $.observed.composite.resource.spec.datasets $datasetType }}
            {{- if not $first }}
            ---
            {{- end }}
            {{- $first = false }}
            {{- $datasetId := printf "%s_%s" (replace "-" "_" $productName) $datasetType }}
            apiVersion: bigquery.gcp.m.upbound.io/v1beta1
            kind: DatasetIAMMember
            metadata:
              name: "{{ $productName }}-{{ $datasetType }}-iam"
              namespace: "{{ $namespace }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: dataset-{{ $datasetType }}-iam
              labels:
                meshifi.io/data-product: "{{ $productName }}"
            spec:
              providerConfigRef:
                kind: ProviderConfig
                name: default
              forProvider:
                project: {{ $projectId }}
                datasetId: {{ $datasetId }}
                role: roles/bigquery.dataEditor
                member: serviceAccount:{{ $saEmail }}
            {{- end }}
            {{- end }}

    - step: automatically-detect-readiness
      functionRef:
        name: crossplane-contrib-function-auto-ready
