apiVersion: meshifi.io/v1alpha1
kind: DataDomain
metadata:
  name: example-domain
  namespace: default
  labels:
    meshifi.io/data-domain: example-domain
spec:
  description: "Example data domain for demonstration"
  owner: "data-team@example.com"
