apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: meshifi-platform
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-provider-creds
      key: credentials
